### ISSUE TITLE
lambda  functions defined on a transition not being called (at least in releases/tags v0.3.3 and v0.3.4)

### ISSUE THREAD

**Issue by jdolter** [StateFactory-Dev/StateFactory#1]
Environment: FTC SDK 9.0.1 / Android Studio / v0.3.4

Noticed that in the FSM update method, you iterate over the current state's potential transitions and cache the 'exitAction' if the transition should fire.

You no longer execute the call on the exitAction Callback object.

**Comment by VikramKaramsetty** [comment]
Hello, thanks for letting me know. The issue has been resolved and will be fixed in the next version of statefactory which should be released soon (or today).
